name: Machine Learning CI Workflow

on:
  push:
    branches: [ main, master ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode dari GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup Python Environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install Dependencies Utama untuk Runner
    - name: Install MLflow & Dependencies
      run: |
        pip install mlflow scikit-learn pandas numpy

    # 4. Jalankan MLflow Project (Re-training Otomatis)
    - name: Run MLflow Project
      run: |
        mlflow run Workflow-CI/MLProject --env-manager local --experiment-name "Mental_Health_Sentiment_CI"

    # 5. Archive/Simpan Artefak Model ke GitHub (Kriteria Skilled)
    - name: Upload Model Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: mlruns/

    # 6. Login ke Docker Hub (Persiapan Kriteria Advance)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 7. Build Docker Image Menggunakan MLflow Build-Docker (Kriteria Advance)
    - name: Build Docker Image via MLflow
      run: |
        MODEL_PATH=$(find mlruns/ -name "MLmodel" | head -n 1 | xargs dirname)
        echo "Menggunakan model dari path: $MODEL_PATH"
        mlflow models build-docker -m "$MODEL_PATH" -n "${{ secrets.DOCKERHUB_USERNAME }}/mental-health-model:latest"
    # 8. Push Docker Image ke Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mental-health-model:latest